# Generated by Django 4.0.1 on 2023-01-21 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_remove_medico_crm_alter_agenda_horario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="O número precisa estar neste formato:                         '91988887777'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone')),
            ],
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(choices=[('1', '07:00 ás 08:00'), ('2', '08:00 ás 09:00'), ('3', '09:00 ás 10:00'), ('4', '10:00 ás 11:00'), ('5', '11:00 ás 12:00'), ('6', '12:00 ás 13:00'), ('7', '13:00 ás 14:00'), ('8', '14:00 ás 15:00'), ('9', '15:00 ás 16:00'), ('10', '16:00 ás 17:00'), ('11', '17:00 ás 18:00')], max_length=10, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='telefone',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="O número precisa estar neste formato:                     '91988887777'.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefone'),
        ),
    ]
