# Generated by Django 4.0.1 on 2023-01-21 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_cliente_alter_agenda_horario_alter_medico_telefone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='email',
        ),
    ]
