# Generated by Django 4.0.1 on 2023-01-21 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_remove_medico_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='medicos.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(choices=[('1', '08:00 ás 09:00'), ('2', '09:00 ás 10:00'), ('3', '10:00 ás 11:00'), ('4', '11:00 ás 12:00'), ('5', '12:00 ás 13:00'), ('6', '13:00 ás 14:00'), ('7', '14:00 ás 15:00'), ('8', '15:00 ás 16:00'), ('9', '16:00 ás 17:00'), ('10', '17:00 ás 18:00')], max_length=10, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='medicos.medico', verbose_name='Profissional'),
        ),
    ]
