# Generated by Django 4.0.1 on 2023-01-21 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_agenda_cliente_alter_agenda_horario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='cliente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='medicos.cliente', verbose_name='Cliente'),
        ),
    ]
