# Generated by Django 4.0.1 on 2023-04-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0011_alter_cliente_options_alter_especialidade_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='horario',
            field=models.CharField(default=None, max_length=30, verbose_name='Horário'),
        ),
    ]
