# Generated by Django 4.0.1 on 2023-04-13 06:10

from django.db import migrations, models
import medicos.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0012_alter_agenda_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.DateField(help_text='Insira a data', validators=[medicos.models.validar_dia])),
                ('relatorio_dia', models.TextField(blank=True, null=True, verbose_name='Relatório do dia')),
            ],
        ),
    ]
