# Generated by Django 4.0.1 on 2023-04-13 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0014_alter_relatorio_dia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='dia',
            new_name='data',
        ),
    ]
