# Generated by Django 4.0.1 on 2023-04-13 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0015_rename_dia_relatorio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
