# Generated by Django 4.0.1 on 2023-04-13 06:54

from django.db import migrations, models
import medicos.models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0016_alter_relatorio_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data',
            field=models.DateField(blank=True, help_text='Insira uma data para agenda', null=True, validators=[medicos.models.validar_dia]),
        ),
    ]
