# Generated by Django 4.0.1 on 2023-04-13 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0017_alter_relatorio_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relatorio',
            old_name='data',
            new_name='dia',
        ),
        migrations.RemoveField(
            model_name='relatorio',
            name='relatorio_dia',
        ),
        migrations.AddField(
            model_name='relatorio',
            name='relatorio',
            field=models.TextField(blank=True, null=True, verbose_name='Relatório'),
        ),
    ]
