# Generated by Django 4.0.1 on 2023-04-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0019_rename_dia_agenda_data_rename_dia_relatorio_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relatorio',
            name='data',
            field=models.DateField(blank=True, help_text='Insira uma data para agenda', null=True),
        ),
    ]
