# Generated by Django 4.0.1 on 2023-04-15 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0021_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='saldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
