# Generated by Django 4.0.1 on 2023-04-15 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0022_alter_caixa_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='saldo',
        ),
    ]
