# Generated by Django 4.0.1 on 2023-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='quantidade_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
