# Generated by Django 4.0.1 on 2023-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0003_caixa_valor_kg_caixa_valor_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada')], default='E', max_length=1),
        ),
    ]
