# Generated by Django 4.0.1 on 2023-05-19 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_transacao_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='valor',
            new_name='valor_kg',
        ),
        migrations.AddField(
            model_name='transacao',
            name='valor_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
