# Generated by Django 4.0.1 on 2023-06-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_alter_cliente_cpf_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada')], default='E', max_length=1),
        ),
    ]
