# Generated by Django 4.0.1 on 2023-06-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_alter_transacao_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='tipo',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1),
        ),
    ]
